[]- id: '1533761576187'
  alias: Bedtime
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - alias: ''
    data:
      entity_id: group.monitors
    service: switch.turn_off
  - data:
      entity_id: group.bedroom_lights
    service: light.turn_off
- id: '1533769689579'
  alias: AlarmOff
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      brightness_pct: '20'
      color_name: cyan
      entity_id: light.bedroom_tower_lamp,light.bedroom_light_strip
    service: light.turn_on
  - data:
      brightness_pct: '10'
      entity_id: light.bedroom_lamp_1
    service: light.turn_on
- id: '1533815178009'
  alias: ArriveHome
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      brightness_pct: '100'
      entity_id: light.bedroom_all_lights
    service: light.turn_on
  - data:
      entity_id: group.monitors
    service: switch.turn_on
- id: '1533817452649'
  alias: LeaveHome
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: light.bedroom_all_lights
    service: light.turn_off
  - data:
      entity_id: group.monitors
    service: switch.turn_off
- id: '1533831051416'
  alias: LeaveTest
  trigger:
  - entity_id: device_tracker.brett_phone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    service: script.away
- id: '1533831925886'
  alias: ArriveTest
  trigger:
  - entity_id: device_tracker.brett_phone
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data: {}
    service: script.home
