homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:
updater:
    reporting: no
sun:
conversation:
tts:
    - platform: google
discovery:
    #ignore:
        #- apple_tv
config:
history:
logbook:

http:
  base_url: !secret http_base_url
  api_password: !secret http_password
  ip_ban_enabled: true
  login_attempts_threshold: 3

cloud:

###########################################
## Components
###########################################

hue:
    bridges:
        - host: 10.0.100.50
          allow_hue_groups: false
          allow_unreachable: true
          
media_player:
    - platform: plex
      entity_namespace: 'plex'

panel_iframe:
    configurator:
        title: Configurator
        icon: mdi:wrench
        url: http://10.0.1.4:3218
        
nest:
    client_id: !secret nest_client_id
    client_secret: !secret nest_client_secret

climate:
    platform: nest
    
tuya:
    username: !secret tuya_username
    password: !secret tuya_password
    country_code: 1

map:

device_tracker:
    - platform: unifi
      username: !secret unifi_username
      password: !secret unifi_password
      host: 10.0.1.110
      port: 8443
      verify_ssl: false
      consider_home: 120
      new_device_defaults:
        track_new_devices: false
        hide_if_away: false
            
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include light_group.yaml
switch: !include switch_group.yaml
