- platform: flux_led
  automatic_add: true
  devices:
    10.0.100.55:
        name: Bedroom Light Strip
        mode: rgb
        
- platform: group
  name: Bedroom All Lights
  entities:
    - light.bedroom_lamp_1
    - light.bedroom_lamp_2
    - light.bedroom_tower_lamp
    - light.bedroom_light_strip

- platform: group
  name: Bedroom Lamp
  entities:
    - light.bedroom_lamp_1
    - light.bedroom_lamp_2