latitude: 0.000
longitude: 0.000
elevation: 0

http_base_url: home.example.com
http_password: password

nest_client_id: client_id
nest_client_secret: client_secret

tuya_username: username
tuya_password: password

unifi_username: username
unifi_password: password