latitude: 0
longitude: 0
elevation: 0

http_base_url: home.example.com
http_password: x

nest_client_id: x
nest_client_secret: x

tuya_username: x
tuya_password: x

unifi_username: x
unifi_password: x